include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Ignore some rules for now to speed up the workshop
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
